site_name: 2024.2 Sagittarius
docs_dir: docs

nav:
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"

theme:
  name: material

use_directory_urls: false